package Telas;

import Banco.ClienteSQL;
import DAO.ClienteDAO;
import DAO.Utilitario;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public final class TelaCliente extends javax.swing.JFrame {

    //Método listar na tabela
    private final Banco.Conexao bd;
    private PreparedStatement st;
    private ResultSet rs;
    private String sql;

    /**
     * Creates new form TelaCliente
     */
    public TelaCliente() {
        initComponents();

        bd = new Banco.Conexao();
        Carregacb();
        carregadados();
        tf_codigo.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dados_pessoais = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        desctipo = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_sobrenome = new javax.swing.JTextField();
        tf_idade = new javax.swing.JTextField();
        cb_tipo = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        bt_pesquisar = new javax.swing.JButton();
        tf_fone = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtpesquisa = new javax.swing.JTextField();
        btnpesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_clientes = new javax.swing.JTable();
        bt_limpar = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_alterar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Clientes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        dados_pessoais.setBackground(new java.awt.Color(200, 221, 242));
        dados_pessoais.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Cadastro de Clientes:");

        javax.swing.GroupLayout dados_pessoaisLayout = new javax.swing.GroupLayout(dados_pessoais);
        dados_pessoais.setLayout(dados_pessoaisLayout);
        dados_pessoaisLayout.setHorizontalGroup(
            dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_pessoaisLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(608, Short.MAX_VALUE))
        );
        dados_pessoaisLayout.setVerticalGroup(
            dados_pessoaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dados_pessoaisLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        JTabbedPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JTabbedPaneKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Sobrenome:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Idade:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Telefone:");

        desctipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        desctipo.setText("Tipo:");

        tf_nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_nome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tf_sobrenome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_sobrenome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tf_idade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_idade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cb_tipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_tipo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("Codigo: ");

        tf_codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_codigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt_pesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_pesquisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\buscar.png")); // NOI18N
        bt_pesquisar.setText("Pesquisar ");
        bt_pesquisar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesquisarActionPerformed(evt);
            }
        });

        tf_fone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_fone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(desctipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_idade, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_fone, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_pesquisar)
                    .addComponent(jLabel8)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desctipo)
                    .addComponent(cb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(tf_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_fone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        JTabbedPane.addTab("Dados pessoais", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Nome:");

        txtpesquisa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpesquisa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpesquisaKeyPressed(evt);
            }
        });

        btnpesquisar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnpesquisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\buscar.png")); // NOI18N
        btnpesquisar.setText("Pesquisar || Atualizar");
        btnpesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpesquisarActionPerformed(evt);
            }
        });

        tabela_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabela_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_clientes);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JTabbedPane.addTab("Consulta de clientes", jPanel3);

        bt_limpar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_limpar.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\novo.png")); // NOI18N
        bt_limpar.setText("Limpar");
        bt_limpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        bt_salvar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_salvar.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\salvar.png")); // NOI18N
        bt_salvar.setText("Cadastrar");
        bt_salvar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_editar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_editar.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\editar.png")); // NOI18N
        bt_editar.setText("Editar");
        bt_editar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_excluir.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\excluir.png")); // NOI18N
        bt_excluir.setText("Excluir");
        bt_excluir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_alterar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        bt_alterar.setIcon(new javax.swing.ImageIcon("C:\\Users\\03595350111\\Documents\\NetBeansProjects\\VendaEXSenac\\src\\Imagens\\modificar.png")); // NOI18N
        bt_alterar.setText("Alterar");
        bt_alterar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        bt_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_alterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dados_pessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(bt_salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(bt_alterar)
                        .addGap(64, 64, 64)
                        .addComponent(bt_editar)
                        .addGap(64, 64, 64)
                        .addComponent(bt_excluir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt_alterar, bt_editar, bt_excluir, bt_limpar, bt_salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dados_pessoais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvar)
                    .addComponent(bt_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_alterar)
                    .addComponent(bt_editar)
                    .addComponent(bt_excluir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {bt_alterar, bt_editar, bt_excluir, bt_limpar, bt_salvar});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        // Editar para alterar

        if (tabela_clientes.getSelectedRow() > -1) {

            JTabbedPane.setSelectedIndex(0);
            bt_salvar.setEnabled(false);
            cb_tipo.setVisible(false);
            desctipo.setVisible(false);
            bt_editar.setEnabled(false);

            tf_codigo.setText(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 0).toString());
            tf_nome.setText(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 1).toString());
            tf_sobrenome.setText(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 2).toString());
            tf_idade.setText(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 3).toString());

            tf_fone.setText(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 4).toString());

          
        } else {
            JOptionPane.showMessageDialog(null, "É preciso selecionar um cliente em consulta de cliente!");
        }

        //new Utilitario().LimpaTela(jPanel2);
        
        
        

    }//GEN-LAST:event_bt_editarActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        // Excluir
        if (tabela_clientes.getSelectedRow() > -1) {
            int escolha = JOptionPane.showConfirmDialog(null, "Deseja excluir?");

            if (escolha == 0) {

                Banco.ClienteSQL msql = new Banco.ClienteSQL();
                msql.cliente.setId_cliente(Integer.parseInt(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 0).toString()));
                if (msql.ExcluirCliente() > 0) {

                    JOptionPane.showMessageDialog(null, "Cliente excluída com sucesso!");

                } else {
                    JOptionPane.showMessageDialog(null, "Erro ao excluir cliente!");

                }
            } else {
                JOptionPane.showMessageDialog(null, "Cancelado pelo usuário!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "É preciso selecionar um cliente em consulta de cliente para excluir!");
        }

        new Utilitario().LimpaTela(jPanel2);
        bt_salvar.setEnabled(true);
        cb_tipo.setVisible(true);
        desctipo.setVisible(true);
        bt_editar.setEnabled(true);
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
        // Limpar dados
        new Utilitario().LimpaTela(jPanel2);
        bt_salvar.setEnabled(true);
        cb_tipo.setVisible(true);
        desctipo.setVisible(true);
        bt_editar.setEnabled(true);


    }//GEN-LAST:event_bt_limparActionPerformed

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        // Cadastrar novo Cliente

        if (tf_nome.getText().trim().length() > 0 && tf_idade.getText().trim().length() > 0
                && tf_sobrenome.getText().trim().length() > 0 && tf_fone.getText().trim().length() > 0) {
            Banco.ClienteSQL cl = new Banco.ClienteSQL();
            TelaCliente.Item i = (TelaCliente.Item) cb_tipo.getSelectedItem();
            cl.cliente.setNome(tf_nome.getText());
            cl.cliente.setSobrenome((tf_sobrenome.getText()));
            cl.cliente.setIdade(Integer.parseInt(tf_idade.getText()));
            cl.cliente.setFone((tf_fone.getText()));
            cl.cliente.setFk_tipo(Integer.parseInt(i.id));
            if (cl.InsereCliente() > 0) {
                JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao fazer cadastro.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não é permitido campo em branco!!");
        }
        new Utilitario().LimpaTela(jPanel2);
    }//GEN-LAST:event_bt_salvarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Carrega a lista


    }//GEN-LAST:event_formWindowActivated

    private void btnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpesquisarActionPerformed
        // Botão pesquisar
        ClienteSQL dao = new ClienteSQL();
        String nome = "%" + txtpesquisa.getText() + "%";
        List<ClienteDAO> lista = dao.buscaClientePorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabela_clientes.getModel();
        dados.setNumRows(0);
        lista.forEach((c) -> {
            dados.addRow(new Object[]{
                c.getId_cliente(),
                c.getNome(),
                c.getSobrenome(),
                c.getIdade(),
                c.getFone()
            });
        });
    }//GEN-LAST:event_btnpesquisarActionPerformed

    private void JTabbedPaneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTabbedPaneKeyPressed
        // TODO add your handling code here:


    }//GEN-LAST:event_JTabbedPaneKeyPressed

    private void bt_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_alterarActionPerformed
        // Alterar cliente
        if (tabela_clientes.getSelectedRow() > -1) {
            if (tf_nome.getText().trim().length() > 0 && tf_idade.getText().trim().length() > 0
                    && tf_sobrenome.getText().trim().length() > 0 && tf_fone.getText().trim().length() > 0) {

                int escolha = JOptionPane.showConfirmDialog(null, "Deseja alterar?");
                if (escolha == 0) {
                    Banco.ClienteSQL altera = new Banco.ClienteSQL();
                    altera.cliente.setNome(tf_nome.getText());
                    altera.cliente.setIdade(Integer.parseInt(tf_idade.getText()));
                    altera.cliente.setSobrenome(tf_sobrenome.getText());
                    altera.cliente.setFone(tf_fone.getText());
                    altera.cliente.setId_cliente(Integer.parseInt(tabela_clientes.getValueAt(tabela_clientes.getSelectedRow(), 0).toString()));
                    if (altera.AlterarCliente() > 0) {
                        JOptionPane.showMessageDialog(null, "Dados do cliente alterado com sucesso!");
                    } else {
                        JOptionPane.showMessageDialog(null, "Erro ao alterar cliente!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Cancelado pelo usuário!");
                }
            } else {
                JOptionPane.showMessageDialog(null, "É preciso editar para alterar!!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "É preciso selecionar um cliente em consulta cliente para alterar!!");
        }
        new Utilitario().LimpaTela(jPanel2);
        bt_salvar.setEnabled(true);
        cb_tipo.setVisible(true);
        desctipo.setVisible(true);
        bt_editar.setEnabled(true);


    }//GEN-LAST:event_bt_alterarActionPerformed

    private void txtpesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpesquisaKeyPressed
        // Pesquisar na caixa de texto
        ClienteSQL dao = new ClienteSQL();
        String nome = "%" + txtpesquisa.getText() + "%";
        List<ClienteDAO> lista = dao.buscaClientePorNome(nome);
        DefaultTableModel dados = (DefaultTableModel) tabela_clientes.getModel();
        dados.setNumRows(0);
        lista.forEach((c) -> {
            dados.addRow(new Object[]{
                c.getId_cliente(),
                c.getNome(),
                c.getSobrenome(),
                c.getIdade(),
                c.getFone()
            });
        });


    }//GEN-LAST:event_txtpesquisaKeyPressed

    private void bt_pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesquisarActionPerformed
        // Busca da primeira tela exatamente 

        String nome = tf_nome.getText();
        ClienteDAO obj = new ClienteDAO();
        ClienteSQL dao = new ClienteSQL();

        obj = dao.consultaPorNome(nome);
        if (obj.getNome() != null) {
            //Exibir os dados do obj nos campos de texto
            bt_salvar.setEnabled(false);
            cb_tipo.setVisible(false);
            desctipo.setVisible(false);
            tf_nome.setText(obj.getNome());
            tf_codigo.setText(String.valueOf(obj.getId_cliente()));
            tf_sobrenome.setText(obj.getSobrenome());
            tf_idade.setText(String.valueOf(obj.getIdade()));
            tf_fone.setText(obj.getFone());
        } else {
            JOptionPane.showMessageDialog(null, "Cliente não encontrado");
        }
        
        //new Utilitario().LimpaTela(jPanel2);
        bt_salvar.setEnabled(true);
        bt_editar.setEnabled(true);

    }//GEN-LAST:event_bt_pesquisarActionPerformed

    private void tabela_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_clientesMouseClicked
        // TODO add your handling code here:

        bt_alterar.setVisible(true);


    }//GEN-LAST:event_tabela_clientesMouseClicked

    /**
     */
    public class Item {

        public String id, descricao;

        public Item(String id, String descricao) {

            this.id = id;
            this.descricao = descricao;

        }

        @Override
        public String toString() {

            return descricao;
        }

    }

    public void Carregacb() {

        sql = "select id_tipo, desc_tipo from tipo";

        try {
            bd.getConnection();
            st = bd.connection.prepareStatement(sql);
            rs = st.executeQuery();
            while (rs.next()) {
                String id = rs.getString(1);
                String descricao = rs.getString(2);
                cb_tipo.addItem(new Item(id, descricao));
            }

        } catch (Exception erro) {

        }

    }

    public void carregadados() {
        try {
            bd.getConnection();
            sql = "Select id_cliente ID, nome NOME, sobrenome SOBRENOME, idade IDADE, fone TELEFONE from cliente";
            st = bd.connection.prepareStatement(sql);
            rs = st.executeQuery();

            DefaultTableModel tableModel = new DefaultTableModel(new String[]{}, 0) {
                public boolean isCellEditable(int rowIndex, int mColIndex) {
                    return false;
                }

            };

            int qtdeColunas = rs.getMetaData().getColumnCount();

            for (int indice = 1; indice <= qtdeColunas; indice++) {
                tableModel.addColumn(rs.getMetaData().getColumnLabel(indice));
            }

            tabela_clientes = new JTable(tableModel);
            DefaultTableModel dtm = (DefaultTableModel) tabela_clientes.getModel();

            while (rs.next()) {
                try {
                    String[] dados = new String[qtdeColunas];
                    for (int i = 1; i <= qtdeColunas; i++) {
                        dados[i - 1] = rs.getString(i);
                    }
                    dtm.addRow(dados);
                    System.out.println();
                } catch (Exception erro) {

                }
                jScrollPane1.setViewportView(tabela_clientes);
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro);
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Ninbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TelaCliente().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JButton bt_alterar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton bt_pesquisar;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JButton btnpesquisar;
    private javax.swing.JComboBox cb_tipo;
    private javax.swing.JPanel dados_pessoais;
    private javax.swing.JLabel desctipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_clientes;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_fone;
    private javax.swing.JTextField tf_idade;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_sobrenome;
    private javax.swing.JTextField txtpesquisa;
    // End of variables declaration//GEN-END:variables
}
